server:
  port: 8890
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8 # 大模型对话中文乱码处理

spring:
  application:
    name: saa-03-prompt
  ai:
    dashscope:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: qwen3.7-max