spring:
  application:
    name: ai-code-helper
  profiles:
    active: local

langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: ${OPENAI_API_KEY}
      embedding-model:
        api-key: ${OPENAI_API_KEY}
        model-name: text-embedding-v4