spring:
  ai:
    mcp:
      server:
        name: image-search-mcp-server
        version: 1.0.0
        type: sync
        stdio: true
        annotation-scanner:
          enabled: true
  main:
    web-application-type: none
    banner-mode: off
